/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AreaCascade: typeof import('./src/components/AreaCascade.vue')['default']
    AreaSelect: typeof import('./src/components/AreaSelect.vue')['default']
    CarCard: typeof import('./src/components/CarCard.vue')['default']
    Charts: typeof import('./src/components/charts/index.vue')['default']
    CommonCard: typeof import('./src/components/CommonCard.vue')['default']
    CommonImgList: typeof import('./src/components/CommonImgList.vue')['default']
    CommonTable: typeof import('./src/components/CommonTable.vue')['default']
    CommonTabs: typeof import('./src/components/CommonTabs.vue')['default']
    CommonTitle: typeof import('./src/components/CommonTitle.vue')['default']
    Dialog: typeof import('./src/components/Dialog.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElCheckboxGroup: typeof import('element-plus/es')['ElCheckboxGroup']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElDatePicker: typeof import('element-plus/es')['ElDatePicker']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElPopover: typeof import('element-plus/es')['ElPopover']
    ElRadio: typeof import('element-plus/es')['ElRadio']
    ElRadioGroup: typeof import('element-plus/es')['ElRadioGroup']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSelectV2: typeof import('element-plus/es')['ElSelectV2']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElTimePicker: typeof import('element-plus/es')['ElTimePicker']
    LeftMenu: typeof import('./src/components/LeftMenu.vue')['default']
    MapChart: typeof import('./src/components/charts/MapChart.vue')['default']
    Nav: typeof import('./src/components/Nav.vue')['default']
    NoData: typeof import('./src/components/NoData.vue')['default']
    Pagination: typeof import('./src/components/Pagination.vue')['default']
    PieChart: typeof import('./src/components/charts/PieChart.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SpecialCard: typeof import('./src/components/SpecialCard.vue')['default']
    SpecialItem: typeof import('./src/components/SpecialItem.vue')['default']
    SvgIcon: typeof import('./src/components/SvgIcon.vue')['default']
    TabBar: typeof import('./src/components/TabBar.vue')['default']
    TopBack: typeof import('./src/components/TopBack.vue')['default']
    TopBar: typeof import('./src/components/TopBar.vue')['default']
    TravelRecordsItem: typeof import('./src/components/TravelRecordsItem.vue')['default']
    ValidateCode: typeof import('./src/components/ValidateCode.vue')['default']
    WarnItem: typeof import('./src/components/WarnItem.vue')['default']
  }
}
