/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AreaCascade: typeof import('./src/components/AreaCascade.vue')['default']
    AreaSelect: typeof import('./src/components/AreaSelect.vue')['default']
    CarCard: typeof import('./src/components/CarCard.vue')['default']
    Charts: typeof import('./src/components/charts/index.vue')['default']
    CommonCard: typeof import('./src/components/CommonCard.vue')['default']
    CommonImgList: typeof import('./src/components/CommonImgList.vue')['default']
    CommonTable: typeof import('./src/components/CommonTable.vue')['default']
    CommonTabs: typeof import('./src/components/CommonTabs.vue')['default']
    CommonTitle: typeof import('./src/components/CommonTitle.vue')['default']
    Dialog: typeof import('./src/components/Dialog.vue')['default']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElPopover: typeof import('element-plus/es')['ElPopover']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    MapChart: typeof import('./src/components/charts/MapChart.vue')['default']
    Nav: typeof import('./src/components/Nav.vue')['default']
    NoData: typeof import('./src/components/NoData.vue')['default']
    Pagination: typeof import('./src/components/Pagination.vue')['default']
    PieChart: typeof import('./src/components/charts/PieChart.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SpecialCard: typeof import('./src/components/SpecialCard.vue')['default']
    SpecialItem: typeof import('./src/components/SpecialItem.vue')['default']
    SvgIcon: typeof import('./src/components/SvgIcon.vue')['default']
    TabBar: typeof import('./src/components/TabBar.vue')['default']
    TopBack: typeof import('./src/components/TopBack.vue')['default']
    TopMenu: typeof import('./src/components/TopMenu.vue')['default']
    TravelRecordsItem: typeof import('./src/components/TravelRecordsItem.vue')['default']
    WarnItem: typeof import('./src/components/WarnItem.vue')['default']
  }
}
