version: '3'

services:
  frontend:
    container_name: 'web-vue'
    image: nginx:latest
    ports:
      - "80:80"           # 将主机的端口80映射到容器的端口80
    restart: always
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf   # 将本地的nginx.conf文件挂载到Nginx容器的配置目录
      - /data/app/dist/:/usr/share/nginx/html/
    environment:
      - TZ=Asia/Shanghai

